Update go.yml

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -22,9 +22,6 @@ jobs:
       run: |
         go get -v -t -d ./...
         if [ -f Gopkg.toml ]; then
-            echo $PWD
-            ls -alh
-            ls -alh /home/runner/work/go-arty/
             mkdir /home/runner/work/go-arty/bin
             export GOPATH=/home/runner/work/go-arty
             export PATH=$PATH:/home/runner/work/go-arty/bin
@@ -33,4 +30,14 @@ jobs:
         fi
 
     - name: Build
-      run: go build -v .
+      run: |
+        go test -v -race ./...
+        # Check that go vet ./... produces a zero diff; clean up any changes afterwards.
+        go vet ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
+        # Check that go fmt ./... produces a zero diff; clean up any changes afterwards.
+        go fmt ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
+        # Check that go generate ./... produces a zero diff; clean up any changes afterwards.
+        go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
+      with:
+        GOPATH: /home/runner/work/go-arty
+        
